### ISSUE TITLE
Efficient knn on large points sets

### ISSUE THREAD

**Issue by QingyongHu** [cgtuebingen/Flex-Convolution#11]
Thanks for your code. 

It seems that  knn_bruteforce function only support point sets less than 8k. As the warning shows:

"point sets greater than 8k are not yet supported!! Change to knn_graph operation!! "

Is there any efficient way to perform knn on large point set? (e.g. when the number of points is 100K or even more), otherwise, I still have to split the scene as many blocks or sample a part of points from the whole scene each time. However, this will undoubtedly lose the geometry information.

**Comment by PatWie** [comment]
This is ongoing work we haven't published yet. Note, in the paper we had a static scene such that a simple kd-tree beforehand did the job. 

But, already have a new network-layer that can compute these neighborhoods on-the-fly for larger point-clouds. Stay tuned :-)

**Comment by MacOS** [comment]
Thank you for you work and publishing your code!

> Note, in the paper we had a static scene such that a simple kd-tree beforehand did the job.
I'm curious, which implementation of kd-tree did you use?

> But, we already have a new network-layer that can compute these neighborhoods on-the-fly for larger point-clouds. Stay tuned :-)
Can you give me any time frame within you plan to make this public?

Thank you in advance!
