### ISSUE TITLE
Question about Table 4 in paper (2D-3D-S dataset)

### ISSUE THREAD

**Issue by francisengelmann** [cgtuebingen/Flex-Convolution#5]
Hi there,

I am curious about the results in Table 4.

First, which experiment is performed here? As I understand from Sec.5 (Experiments) it is semantic segmentation, i.e. for each point you predict a semantic label (one out of N classes, here N=13 for 2D-3D Stanford http://buildingparser.stanford.edu/images/3Dmodal.png while clutter was not evaluated).

Second, I am wondering how you compute the AP? For semantic segmentation, the mean Intersection-over-Union (IoU) is more common. In fact, the AP is often used when reporting **instance segmentation** scores. The scores from the other methods [2, 17, 28] in Table 4 are all referring to instance segmentation, not semantic segmentation (which brings me back to the first question).
Assuming you are not comparing your semantic segmentation results to the much harder task of instance segmentation, how do you perform instance segmentation? The paper does not give an information on this, while Fig. 6 shows qualitative results only for semantic segmentation task, not instance segmentation.

**Comment by avodo** [comment]
Thanks for the feedback. However, we want to keep the github issues for the implementation details only. But we are open to discuss your point via email or skype/phone in depth.

**Comment by francisengelmann** [comment]
Thanks for your reply avodo.
Please feel free to contact me at engelmann@vision.rwth-aachen.de
