### ISSUE TITLE
Compile Problem requires 'export CUB_INC=/path/to/cub

### ISSUE THREAD

**Issue by MEIXuYan** [cgtuebingen/Flex-Convolution#6]
Thanks for sharing your code.
I got a problem when complie the usr_op, showing as below:
(I'm not familiar with the Cuda-CUB)
```
-- Reuse cached information from TensorFlow 1.9.0 
-- No TensorFlow-CC-LIBRARY detected
-- No TensorFlow source repository detected
-- CUDA_INCLUDE_DIRS: /usr/local/cuda-9.0/include
-- CUDA_SAMPLE_INC: /samples/common/inc
CMake Error at CMakeLists.txt:26 (message):
  requires 'export CUB_INC=/path/to/cub
```
I'm work with ubuntu 14.04, cuda 9.0, tensorflow-gpu 1.9.0, GTX 1080Ti.
Hope you can fix it, thank you.

**Comment by PatWie** [comment]
See the updated build instructions in the README.md from commit 129cfefebf1dffa074d030be94065bdebc74f830. The copy-and-paste solution would be

```bash
cd /tmp
wget https://github.com/NVlabs/cub/archive/v1.8.0.zip
unzip v1.8.0.zip -d $HOME/libs
export CUB_INC=$HOME/libs/cub-1.8.0/
rm /tmp/v1.8.0.zip
```

Feel free to ask, if there is anything unclear.

**Comment by david-klindt** [comment]
K->k also needs to changed in example.py lines 45, 59
