### ISSUE TITLE
compile problem with helper_cuda.h

### ISSUE THREAD

**Issue by david-klindt** [cgtuebingen/Flex-Convolution#7]
Hi I am getting the following error during building on ubuntu 16.04, cuda 9.0:

-- Reuse cached information from TensorFlow 1.9.0 
-- No TensorFlow-CC-LIBRARY detected
-- No TensorFlow source repository detected
-- CUDA_INCLUDE_DIRS: /usr/local/cuda/include
-- CUDA_SAMPLE_INC: /samples/common/inc
-- Use Cuda-CUB from /root/libs/cub-1.8.0/
-- will build custom TensorFlow operation "flex_conv" (CPU+GPU)
-- will build custom TensorFlow operation "flex_deconv" (CPU+GPU)
-- will build custom TensorFlow operation "flex_pool" (CPU+GPU)
-- will build custom TensorFlow operation "knn_bruteforce" (CPU+GPU)
-- Configuring done
-- Generating done
-- Build files have been written to: HOME/Flex-Convolution/user_ops
[  4%] Building NVCC (Device) object CMakeFiles/knn_bruteforce_op_cu.dir/kernels/knn_bruteforce_op_cu_generated_knn_bruteforce_kernel_gpu.cu.cc.o
[ 20%] Built target flex_pool_op_cu
[ 20%] Built target flex_deconv_op_cu
[ 29%] Built target flex_conv_op_cu
HOME/Flex-Convolution/user_ops/kernels/knn_bruteforce_kernel_gpu.cu.cc:25:25: fatal error: helper_cuda.h: No such file or directory
compilation terminated.

**Comment by PatWie** [comment]
The dependency is remove now in 01dcd7555e69eccefef0f0578ae5c290ba582358
